

class HW_BATTLE_EFFICIENCY_TYPES(object):
    HALLOWEEN_REPAIR = 'halloweenRepair'
    HALLOWEEN_REPAIR_OTHER = 'halloweenRepairOther'
    HALLOWEEN_REPAIR_BY_OTHER = 'halloweenRepairByOther'
    HALLOWEEN_DMG_VAMPIRE = 'halloweenDmgVampire'
    HALLOWEEN_AOE_BURN = 'halloweenAoeBurn'
    HALLOWEEN_AOE_DAMAGE = 'halloweenAoeDamage'
    HALLOWEEN_MODULES_DAMAGE_BLOCKED = 'halloweenModulesDanageBlocked'
    HALLOWEEN_PASSIVE_IGNITE = 'halloweenPassiveIgnite'
    HALLOWEEN_PASSIVE_VAMPIRE = 'halloweenPassiveVampire'
    HALLOWEEN_AOE_BOSS_BURN = 'halloweenAoeBossBurn'
    HALLOWEEN_BOMBER_EXPLOSION = 'halloweeBomberExplosion'
    HALLOWEEN_SHELLS_PICKUP = 'halloweenShellPickup'
    HALLOWEEN_SHELLS_RECEIVE = 'halloweenShellReceive'
    HALLOWEEN_SOULS_PICKUP = 'halloweenSoulsPickup'
    HALLOWEEN_SOULS_DRAINED = 'halloweenSoulsDrained'
    HALLOWEEN_SOULS_RECEIVE = 'halloweenSoulsReceive'
    HALLOWEEN_SOULS_REFUND = 'halloweenSoulsRefund'
    HALLOWEEN_HANGAR_ITEMS_PICKUP = 'halloweenHangarItemsPickup'
    HALLOWEEN_HANGAR_ITEMS_RECEIVE = 'halloweenHangarItemsReceive'
    HALLOWEEN_DMG_VAMPIRE_RECEIVED = 'halloweenDmgVampireReceived'
    HALLOWEEN_AOE_DAMAGE_RECEIVED = 'halloweenAoeDamageReceived'
    HALLOWEEN_SHOT_AOE_DAMAGE = 'halloweenShotAoeDamage'
    HALLOWEEN_SHOT_AOE_DRAIN_ENEMY_HP = 'halloweenShotAoeDrainEnemyHp'
    HALLOWEEN_SHOT_AOE_STUN = 'halloweenShotAoeStun'
    HALLOWEEN_IGNITE_DAMAGE_RECEIVED = 'halloweenIgniteDamageReceived'
    HALLOWEEN_STUN_DAMAGE_RECEIVED = 'halloweenStunDamageReceived'
    HALLOWEEN_DAMAGE_OVERTIME_RECEIVED = 'halloweenDamageOvertimeReceived'
    HALLOWEEN_ANOMALY_PICKUP = 'halloweenAnomalyPickup'
    HALLOWEEN_ANOMALY_RECEIVE = 'halloweenAnomalyReceive'
    HALLOWEEN_BOMBER_RESIST = 'halloweenBomberResist'
    HALLOWEEN_INSTANT_KILL = 'halloweenInstantKill'
    HALLOWEEN_CORROSION_DAMAGE = 'halloweenCorrosionDamage'
    HALLOWEEN_STOMPING_DAMAGE = 'halloweenStompingDamage'